# Docker compose to run the php application
version: "3"

services:
  thinkidownloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ThinkiDownloader
    working_dir: /app
    environment:
      - COURSE_LINK=${COURSE_LINK}
      - CLIENT_DATE=${CLIENT_DATE}
      - COOKIE_DATA=${COOKIE_DATA}
      - VIDEO_DOWNLOAD_QUALITY=${VIDEO_DOWNLOAD_QUALITY}
      - COURSE_NAME=${COURSE_NAME}
      - CHECK_UPDATES_ONLY=${CHECK_UPDATES_ONLY}
    volumes:
      - .:/app
      - ../../../data/courses/${COURSE_NAME}:/app/${COURSE_NAME}
    command: >
      sh -c "php thinkidownloader3.php ${COURSE_LINK} && cp ${COURSE_NAME}/*.json /app/${COURSE_NAME}/ || true"
