# Docker compose to run the php application
version: "3"

services:
  thinkidownloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ThinkiDownloader
    working_dir: /app
    volumes:
      - .:/app
      - ../../../data/courses/${COURSE_NAME}:/app/${COURSE_NAME}
    command: >
      sh -c "php thinkidownloader3.php --json ${COURSE_DATA_FILE} && mkdir -p /app/${COURSE_NAME} && cp ${COURSE_NAME}/*.json /app/${COURSE_NAME}/ || true"
    environment:
      - COURSE_DATA_FILE=${COURSE_DATA_FILE}
      - CLIENT_DATE=${CLIENT_DATE}
      - COOKIE_DATA=${COOKIE_DATA}
      - VIDEO_DOWNLOAD_QUALITY=${VIDEO_DOWNLOAD_QUALITY}
      - COURSE_NAME=${COURSE_NAME}
