site_name: ThinkiPlex Documentation
site_description: Documentation for ThinkiPlex - Thinkific course downloader and organizer for Plex
repo_url: https://github.com/yourusername/thinkiplex
theme:
  name: material
  palette:
    primary: indigo
    accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Guides:
      - Installation: guides/installation.md
      - Configuration: guides/configuration.md
      - Authentication: guides/authentication.md
      - Transcription & AI: guides/transcription.md
      - PDF Generation: guides/pdf-generation.md
      - Development: guides/development.md
  - API Reference:
      - CLI: api/cli.md
      - Configuration: api/config.md
      - Downloader: api/downloader.md
      - Organizer: api/organizer.md
      - PDF Generation: api/pdf.md
      - Transcription: api/transcription.md
      - Utils: api/utils.md
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
